import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { AlertTriangle, ChevronDown, ChevronUp, Filter } from "lucide-react";
import Card, { CardTitle } from "../components/Card";

const SEV_COLOR = { critical: "#ff2d55", high: "#ff9f0a", medium: "#ffd60a", low: "#30d158" };
const SEV_ORDER = { critical: 0, high: 1, medium: 2, low: 3 };
const FILTERS   = ["all", "critical", "high", "medium", "low"];

function AlertRow({ inc, index }) {
  const [open, setOpen] = useState(false);
  const c = SEV_COLOR[inc.severity] || "#64748b";
  const aptSet = [...new Set(inc.iocs?.map(i => i.apt_attribution).filter(Boolean))];

  return (
    <motion.div
      layout
      initial={{ opacity: 0, y: 16 }}
      animate={{ opacity: 1, y: 0 }}
      exit={{ opacity: 0, y: -8 }}
      transition={{ delay: index * 0.04 }}
      className="rounded-xl overflow-hidden mb-3"
      style={{ border: `1px solid ${c}30`, background: `${c}08` }}
    >
      {/* Header row */}
      <button className="w-full flex items-center gap-3 px-4 py-3 text-left" onClick={() => setOpen(o => !o)}>
        <span className="w-2.5 h-2.5 rounded-full blink shrink-0" style={{ background: c }} />
        <span className="text-xs font-black w-20 shrink-0" style={{ color: c, textShadow: `0 0 8px ${c}80` }}>
          {inc.severity?.toUpperCase()}
        </span>
        <span className="font-mono text-xs text-[#64748b]">{inc.id?.slice(0, 8)}</span>

        {/* MITRE badges */}
        <div className="flex gap-1 flex-wrap">
          {inc.mitre_techniques?.slice(0, 3).map(t => (
            <span key={t} className="text-xs bg-[#00d4ff15] text-[#00d4ff] border border-[#00d4ff25] rounded px-1.5 py-0.5">
              {t}
            </span>
          ))}
        </div>

        <span className="ml-auto text-xs text-[#64748b]">{inc.detected_at?.slice(11, 19)}</span>
        <span className="text-lg font-black mx-2" style={{ color: c }}>{inc.risk_score}</span>
        {open ? <ChevronUp size={14} className="text-[#64748b]" /> : <ChevronDown size={14} className="text-[#64748b]" />}
      </button>

      {/* Expanded detail */}
      <AnimatePresence>
        {open && (
          <motion.div initial={{ height: 0, opacity: 0 }} animate={{ height: "auto", opacity: 1 }}
            exit={{ height: 0, opacity: 0 }} transition={{ duration: 0.25 }}
            className="border-t px-4 py-3 space-y-3" style={{ borderColor: c + "25" }}>

            {/* Summary */}
            <p className="text-sm text-[#e8f4f8] leading-relaxed">
              {inc.summary || "CISO executive summary will be generated by LLM in Phase 3."}
            </p>

            <div className="grid grid-cols-3 gap-3 text-xs">
              {/* Assets */}
              <div>
                <div className="text-[#64748b] mb-1 uppercase tracking-wider text-xs">Targeted Assets</div>
                <div className="space-y-1">
                  {inc.targeted_assets?.length ? inc.targeted_assets.map(a => (
                    <span key={a} className="block bg-[#0a1628] border border-[#1e3a5f] rounded px-2 py-1">{a}</span>
                  )) : <span className="text-[#64748b]">Unknown</span>}
                </div>
              </div>

              {/* Compliance */}
              <div>
                <div className="text-[#64748b] mb-1 uppercase tracking-wider text-xs">Compliance Breaches</div>
                <div className="space-y-1">
                  {inc.compliance_breaches?.length ? inc.compliance_breaches.map(b => (
                    <span key={b} className="block bg-red-500/10 border border-red-500/30 text-red-400 rounded px-2 py-1">{b}</span>
                  )) : <span className="text-green-400">None</span>}
                </div>
              </div>

              {/* APT */}
              <div>
                <div className="text-[#64748b] mb-1 uppercase tracking-wider text-xs">APT Attribution</div>
                <div className="space-y-1">
                  {aptSet.length ? aptSet.map(a => (
                    <span key={a} className="block bg-orange-500/10 border border-orange-500/30 text-orange-400 rounded px-2 py-1 uppercase">
                      {a}
                    </span>
                  )) : <span className="text-[#64748b]">Unknown</span>}
                </div>
              </div>
            </div>

            {/* IOC count */}
            <div className="text-xs text-[#64748b]">
              {inc.iocs?.length || 0} IOCs correlated into this incident
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </motion.div>
  );
}

export default function Alerts({ incidents }) {
  const [filter, setFilter] = useState("all");
  const filtered = [...incidents]
    .filter(i => filter === "all" || i.severity === filter)
    .sort((a, b) => (SEV_ORDER[a.severity] ?? 3) - (SEV_ORDER[b.severity] ?? 3));

  const counts = FILTERS.slice(1).reduce((acc, s) =>
    ({ ...acc, [s]: incidents.filter(i => i.severity === s).length }), {});

  return (
    <div className="space-y-4">
      {/* Filter bar */}
      <Card delay={0}>
        <div className="flex items-center gap-3 flex-wrap">
          <Filter size={14} className="text-[#64748b]" />
          <span className="text-xs text-[#64748b] uppercase tracking-wider">Filter:</span>
          {FILTERS.map(f => {
            const c = SEV_COLOR[f] || "#00d4ff";
            const active = filter === f;
            return (
              <motion.button key={f} whileHover={{ scale: 1.05 }} whileTap={{ scale: 0.96 }}
                onClick={() => setFilter(f)}
                className="text-xs px-3 py-1.5 rounded-lg border font-semibold transition-all"
                style={{
                  borderColor: active ? c : "#1e3a5f",
                  background: active ? c + "20" : "transparent",
                  color: active ? c : "#64748b",
                }}>
                {f.toUpperCase()}
                {f !== "all" && counts[f] > 0 && (
                  <span className="ml-1.5 text-xs opacity-70">({counts[f]})</span>
                )}
              </motion.button>
            );
          })}
          <span className="ml-auto text-xs text-[#64748b]">{filtered.length} incident{filtered.length !== 1 ? "s" : ""}</span>
        </div>
      </Card>

      {/* Alert list */}
      <div>
        <AnimatePresence mode="popLayout">
          {filtered.length === 0
            ? <motion.p key="empty" initial={{ opacity: 0 }} animate={{ opacity: 1 }}
                className="text-center text-[#64748b] text-sm py-16">
                No {filter !== "all" ? filter : ""} incidents — system clean.
              </motion.p>
            : filtered.map((inc, i) => <AlertRow key={inc.id} inc={inc} index={i} />)
          }
        </AnimatePresence>
      </div>
    </div>
  );
}
